AWSTemplateFormatVersion: 2010-09-09
Description: >-
  fastify-sam-lambda
Transform:
- AWS::Serverless-2016-10-31
Resources:
  getOrderDetails:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple get api end point hosted with Lambda + API Gateway integration using Fastify
      Events:
        Api:
          Type: Api
          Properties:
            Path: /order
            Method: GET
  postOrder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method
      Events:
        Api:
          Type: Api
          Properties:
            Path: /order
            Method: POST
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
